name: Pages

on:
  push:
    branches:
      - master  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # deploying branch
      - name: TencentCloud-Save Private Key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{secrets.DEPLOY_KEY}}
      - name: TencentCloud-Scan Public Keys
        run: ssh-keyscan vantis.club >> ~/.ssh/known_hosts
      - name: TencentCloud-Deploy
        run: rsync -av --delete public/ root@vantis.club:/usr/share/nginx/vantis.club

